name: xfce-aero-vista
description: XFCE with Vista-like theme, with some modifications.
base-image: ghcr.io/fiftydinar/arch-bootc
image-version: latest

modules:
  - type: pacman
    install:
      packages:
        # bootloader stuff
        - grub
        - efibootmgr
        # GPU acceleration - OpenGL, Vulkan, video decoding/encoding (I won't cover proprietary Nvidia by default)
        - mesa
        - vulkan-radeon
        - vulkan-intel
        - vulkan-nouveau
        - vulkan-swrast
        - libva-intel-driver
        - intel-media-driver
        - libvpl
        - vpl-gpu-rt
        - intel-media-sdk
        - virglrenderer
        - qemu-guest-agent
        - spice-vdagent
        - xf86-video-qxl
        - xf86-video-fbdev
        # DE stuff
        - xorg
        - xfce4
        - pasystray
        - cbatticon
        - obsidian-icon-theme
        - kvantum-qt5
        - kvantum
        - qt5ct
        - qt6ct
        - lightdm
        - lightdm-gtk-greeter
  - type: script
    snippets:
      # Install script to make AUR package easily
      - "wget --directory-prefix=/tmp/arch-tools/ https://raw.githubusercontent.com/pkgforge-dev/Anylinux-AppImages/refs/heads/main/useful-tools/make-aur-package.sh"
      - "chmod +x /tmp/arch-tools/make-aur-package.sh"
      # Install compiz, emerald
      - "cd /tmp/arch-tools && /tmp/arch-tools/make-aur-package.sh gtk2"
      - "cd /tmp/arch-tools && /tmp/arch-tools/make-aur-package.sh libwnck"
      - "cd /tmp/arch-tools && /tmp/arch-tools/make-aur-package.sh compiz"
      - "cd /tmp/arch-tools && /tmp/arch-tools/make-aur-package.sh emerald"
      # Cleanup
      - "rm -r /tmp/arch-tools/"
      # Other stuff
      - "sed -i 's|bootc upgrade --apply --quiet|bootc upgrade --quiet|g' /usr/lib/systemd/system/bootc-fetch-apply-updates.service"
      # Fix bootc-image-builder not liking 2 dots in VERSION_ID for some reason
      - |
        sed -E -i "s/^(VERSION_ID=)(['\"]?)([0-9]{8}\.[0-9]+)\.([0-9]+)(['\"]?)/\\1\"\\3-\\4\"/" /etc/os-release
  - type: systemd
    system:
      enabled:
        - lightdm.service
  - type: signing
  - type: script
    snippets:
      # Show all installed packages sorted by size
      - |
        pacman -Qi | awk -F': ' '/Name/ {n=$2} /Installed Size/ {s=$2} n && s {print n, s; n=s=""}' | column -t | grep MiB | sort -nk 2
