name: xfce-aero-vista
description: XFCE with Vista-like theme, with some modifications.
base-image: ghcr.io/fiftydinar/arch-bootc
image-version: latest

modules:
  - type: pacman
    install:
      packages:
        # GPU acceleration - OpenGL, Vulkan, video decoding/encoding (I won't cover proprietary Nvidia by default)
        - mesa
        - vulkan-radeon
        - vulkan-intel
        - vulkan-nouveau
        - vulkan-swrast
        - libva-intel-driver
        - intel-media-driver
        - libvpl
        - vpl-gpu-rt
        - intel-media-sdk
        # DE stuff
        - xorg
        - xfce4
        - pasystray
        - cbatticon
        - obsidian-icon-theme
        - kvantum-qt5
        - kvantum
        - qt5ct
        - qt6ct
  - type: script
    snippets:
      # Install script to make AUR package easily
      - "wget --directory-prefix=/tmp/arch-tools/ https://raw.githubusercontent.com/pkgforge-dev/Anylinux-AppImages/refs/heads/main/useful-tools/make-aur-package.sh"
      - "chmod +x /tmp/arch-tools/make-aur-package.sh"
      # Install compiz, ccsm-gtk3, emerald
      - "cd /tmp/arch-tools && /tmp/arch-tools/make-aur-package.sh libwnck"
      - "cd /tmp/arch-tools && /tmp/arch-tools/make-aur-package.sh compiz"
      - "cd /tmp/arch-tools && /tmp/arch-tools/make-aur-package.sh ccsm-gtk3"
      - "cd /tmp/arch-tools && /tmp/arch-tools/make-aur-package.sh emerald"
      # Cleanup
      - "rm -r /tmp/arch-tools/"
  - type: signing
  - type: script
    snippets:
      - "pacman -Q"
